# Mago configuration file
# For more information, see https://mago.carthage.software/#/getting-started/configuration
php_version = "8.4.0"

[source]
paths = ["source/php/"]
includes = ["vendor"]
excludes = []

[format]
print_width = 120
tab_width = 4
use_tabs = false

[linter]
default_plugins = true
plugins = ["php-unit"]